-- DDL Oracle para MiniMarket 'Doña Marta'
SET DEFINE OFF;
-- Crear secuencias pedidas
CREATE SEQUENCE seq_salud START WITH 2050 INCREMENT BY 10 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_empleado START WITH 750 INCREMENT BY 3 NOCACHE NOCYCLE;

-- TABLAS CATALOGO
CREATE TABLE REGION (
  id_region NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  nom_region VARCHAR2(255) NOT NULL
);

CREATE TABLE COMUNA (
  id_comuna NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  nom_comuna VARCHAR2(100) NOT NULL,
  cod_region NUMBER NOT NULL,
  CONSTRAINT fk_comuna_region FOREIGN KEY (cod_region) REFERENCES REGION(id_region)
);

CREATE TABLE AFP (
  id_afp NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 210 INCREMENT BY 6) PRIMARY KEY,
  nom_afp VARCHAR2(255) NOT NULL
);

CREATE TABLE SALUD (
  id_salud NUMBER PRIMARY KEY,
  nom_salud VARCHAR2(40) NOT NULL
);

CREATE TABLE MEDIO_PAGO (
  id_mpag NUMBER PRIMARY KEY,
  nombre_mpag VARCHAR2(50) NOT NULL
);

CREATE TABLE MARCA (
  id_marca NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  nombre_marca VARCHAR2(255) NOT NULL,
  CONSTRAINT unq_marca_nombre UNIQUE (nombre_marca)
);

CREATE TABLE CATEGORIA (
  id_categoria NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  nombre_categoria VARCHAR2(255) NOT NULL
);

CREATE TABLE PROVEEDOR (
  id_proveedor NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  nombre_proveedor VARCHAR2(150) NOT NULL,
  rut_proveedor VARCHAR2(20),
  telefono VARCHAR2(20),
  email VARCHAR2(200),
  direccion VARCHAR2(200),
  cod_comuna NUMBER,
  CONSTRAINT fk_proveedor_comuna FOREIGN KEY (cod_comuna) REFERENCES COMUNA(id_comuna),
  CONSTRAINT unq_proveedor_email UNIQUE (email)
);

CREATE TABLE PRODUCTO (
  id_producto NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  nombre_producto VARCHAR2(100) NOT NULL,
  precio_unitario NUMBER(12,2) NOT NULL,
  origen_nacional CHAR(1) CHECK (origen_nacional IN ('S','N')),
  stock_minimo NUMBER(10) DEFAULT 3 CHECK (stock_minimo >= 3),
  activo CHAR(1) DEFAULT 'S' CHECK (activo IN ('S','N')),
  cod_marca NUMBER,
  cod_categoria NUMBER,
  cod_proveedor NUMBER,
  CONSTRAINT fk_producto_marca FOREIGN KEY (cod_marca) REFERENCES MARCA(id_marca),
  CONSTRAINT fk_producto_categoria FOREIGN KEY (cod_categoria) REFERENCES CATEGORIA(id_categoria),
  CONSTRAINT fk_producto_proveedor FOREIGN KEY (cod_proveedor) REFERENCES PROVEEDOR(id_proveedor)
);

-- EMPLEADO y subtipos
CREATE TABLE EMPLEADO (
  id_empleado NUMBER PRIMARY KEY,
  rut_empleado VARCHAR2(15) UNIQUE,
  nombre_empleado VARCHAR2(50) NOT NULL,
  apellido_paterno VARCHAR2(50) NOT NULL,
  apellido_materno VARCHAR2(50),
  fecha_contratacion DATE,
  sueldo_base NUMBER(12,2) NOT NULL,
  bono_jefatura NUMBER(12,2),
  activo CHAR(1) DEFAULT 'S' CHECK (activo IN ('S','N')),
  tipo_empleado VARCHAR2(25),
  cod_salud NUMBER,
  cod_afp NUMBER,
  CONSTRAINT fk_empleado_salud FOREIGN KEY (cod_salud) REFERENCES SALUD(id_salud),
  CONSTRAINT fk_empleado_afp FOREIGN KEY (cod_afp) REFERENCES AFP(id_afp),
  CONSTRAINT chk_sueldo_min CHECK (sueldo_base >= 400000)
);

CREATE TABLE VENDEDOR (
  id_empleado NUMBER PRIMARY KEY,
  comision_venta NUMBER(5,4) DEFAULT 0,
  CONSTRAINT fk_vendedor_emp FOREIGN KEY (id_empleado) REFERENCES EMPLEADO(id_empleado),
  CONSTRAINT chk_comision_vendedor CHECK (comision_venta >= 0 AND comision_venta <= 0.25)
);

CREATE TABLE ADMINISTRATIVO (
  id_empleado NUMBER PRIMARY KEY,
  cargo VARCHAR2(100),
  CONSTRAINT fk_admin_emp FOREIGN KEY (id_empleado) REFERENCES EMPLEADO(id_empleado)
);

-- VENTA y DETALLE_VENTA
CREATE TABLE VENTA (
  id_venta NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 5050 INCREMENT BY 3) PRIMARY KEY,
  fecha_venta DATE DEFAULT SYSDATE,
  total_venta NUMBER(12,2),
  cod_mpago NUMBER,
  cod_empleado NUMBER,
  CONSTRAINT fk_venta_mpago FOREIGN KEY (cod_mpago) REFERENCES MEDIO_PAGO(id_mpag),
  CONSTRAINT fk_venta_empleado FOREIGN KEY (cod_empleado) REFERENCES EMPLEADO(id_empleado)
);

CREATE TABLE DETALLE_VENTA (
  cod_venta NUMBER NOT NULL,
  cod_producto NUMBER NOT NULL,
  cantidad NUMBER NOT NULL,
  CONSTRAINT pk_detalle_venta PRIMARY KEY (cod_venta, cod_producto),
  CONSTRAINT fk_detventa_venta FOREIGN KEY (cod_venta) REFERENCES VENTA(id_venta),
  CONSTRAINT fk_detventa_producto FOREIGN KEY (cod_producto) REFERENCES PRODUCTO(id_producto),
  CONSTRAINT chk_detventa_cantidad CHECK (cantidad > 0)
);

-- Índices recomendados
CREATE INDEX ix_producto_proveedor ON PRODUCTO(cod_proveedor);
CREATE INDEX ix_venta_empleado ON VENTA(cod_empleado);

COMMIT;

-- Triggers para usar secuencias en EMPLEADO y SALUD (asignación automática si se inserta NULL)
CREATE OR REPLACE TRIGGER trg_emp_before_ins
BEFORE INSERT ON EMPLEADO
FOR EACH ROW
BEGIN
  IF :NEW.id_empleado IS NULL THEN
    :NEW.id_empleado := seq_empleado.NEXTVAL;
  END IF;
END;
/
CREATE OR REPLACE TRIGGER trg_salud_before_ins
BEFORE INSERT ON SALUD
FOR EACH ROW
BEGIN
  IF :NEW.id_salud IS NULL THEN
    :NEW.id_salud := seq_salud.NEXTVAL;
  END IF;
END;
/
COMMIT;

-- Sample inserts para MiniMarket Doña Marta
SET DEFINE OFF;
-- Regiones y comunas
INSERT INTO REGION(nom_region) VALUES('Región de Los Lagos');
INSERT INTO REGION(nom_region) VALUES('Región Metropolitana');

INSERT INTO COMUNA(nom_comuna,cod_region) VALUES('Puerto Montt',1);
INSERT INTO COMUNA(nom_comuna,cod_region) VALUES('Santiago',2);

-- Medios de pago
INSERT INTO MEDIO_PAGO(id_mpag,nombre_mpag) VALUES (1,'Efectivo');
INSERT INTO MEDIO_PAGO(id_mpag,nombre_mpag) VALUES (2,'Transferencia');
INSERT INTO MEDIO_PAGO(id_mpag,nombre_mpag) VALUES (3,'Tarjeta');

-- Marcas y categorias
INSERT INTO MARCA(nombre_marca) VALUES('LaLechera');
INSERT INTO MARCA(nombre_marca) VALUES('CaféSol');

INSERT INTO CATEGORIA(nombre_categoria) VALUES('Lácteos');
INSERT INTO CATEGORIA(nombre_categoria) VALUES('Bebidas');

-- Proveedores
INSERT INTO PROVEEDOR(nombre_proveedor,rut_proveedor,telefono,email,direccion,cod_comuna)
VALUES ('Distribuciones Sur','76.543.210-9','612345678','contacto@distsur.cl','Av. Principal 100',1);

INSERT INTO PROVEEDOR(nombre_proveedor,rut_proveedor,telefono,email,direccion,cod_comuna)
VALUES ('Proveedor Central','11.111.111-1','612222333','ventas@provcentral.cl','Calle 123',2);

-- Productos
INSERT INTO PRODUCTO(nombre_producto,precio_unitario,origen_nacional,stock_minimo,activo,cod_marca,cod_categoria,cod_proveedor)
VALUES ('Leche Entera 1L',1200,'S',5,'S',1,1,1);

INSERT INTO PRODUCTO(nombre_producto,precio_unitario,origen_nacional,stock_minimo,activo,cod_marca,cod_categoria,cod_proveedor)
VALUES ('Café Molido 250g',2500,'N',3,'S',2,2,2);

-- AFP (identity start 210 increment 6)
INSERT INTO AFP(nom_afp) VALUES('AFP Modelo');
INSERT INTO AFP(nom_afp) VALUES('AFP Provida');

-- SALUD (use sequence)
INSERT INTO SALUD(nom_salud) VALUES('Fonasa');
INSERT INTO SALUD(nom_salud) VALUES('Isapre ABC');

-- Empleados (some as vendedores/administrativos)
-- Using trigger to assign id_empleado from seq_empleado (start 750 increment 3)
INSERT INTO EMPLEADO(rut_empleado,nombre_empleado,apellido_paterno,apellido_materno,fecha_contratacion,sueldo_base,bono_jefatura,activo,tipo_empleado,cod_salud,cod_afp)
VALUES ('11.222.333-4','María','González','Pérez',TO_DATE('2018-01-10','YYYY-MM-DD'),450000,20000,'S','ADMIN',2050,210);

INSERT INTO EMPLEADO(rut_empleado,nombre_empleado,apellido_paterno,apellido_materno,fecha_contratacion,sueldo_base,bono_jefatura,activo,tipo_empleado,cod_salud,cod_afp)
VALUES ('22.333.444-5','Pedro','Soto','Lira',TO_DATE('2019-06-15','YYYY-MM-DD'),520000,15000,'S','VEND',2060,216);

INSERT INTO EMPLEADO(rut_empleado,nombre_empleado,apellido_paterno,apellido_materno,fecha_contratacion,sueldo_base,bono_jefatura,activo,tipo_empleado,cod_salud,cod_afp)
VALUES ('33.444.555-6','Ana','Rojas','Caro',TO_DATE('2020-03-20','YYYY-MM-DD'),600000,NULL,'S','VEND',2050,222);

-- Registrar roles
-- We assume the first seq_empleado values are 750,753,756 respectively
INSERT INTO VENDEDOR(id_empleado,comision_venta) VALUES (750,0.10);
INSERT INTO ADMINISTRATIVO(id_empleado,cargo) VALUES (753,'Encargada');

-- Ventas (id_venta identity starts 5050)
INSERT INTO VENTA(fecha_venta,total_venta,cod_mpago,cod_empleado) VALUES (TO_DATE('2025-09-01','YYYY-MM-DD'),3700,1,750);
-- Detalle venta
INSERT INTO DETALLE_VENTA(cod_venta,cod_producto,cantidad) VALUES (5050,1,2);
INSERT INTO DETALLE_VENTA(cod_venta,cod_producto,cantidad) VALUES (5050,2,1);

COMMIT;

-- Consultas requeridas (Informe 1 y Informe 2)
-- INFORME 1:
SELECT
  e.id_empleado AS IDENTIFICADOR,
  (e.nombre_empleado || ' ' || e.apellido_paterno || ' ' || NVL(e.apellido_materno,'')) AS "NOMBRE COMPLETO",
  e.sueldo_base AS SALARIO,
  e.bono_jefatura AS BONIFICACION,
  (e.sueldo_base + e.bono_jefatura) AS "SALARIO SIMULADO"
FROM EMPLEADO e
WHERE e.activo = 'S' AND e.bono_jefatura IS NOT NULL
ORDER BY (e.sueldo_base + e.bono_jefatura) DESC, e.apellido_paterno DESC;

-- INFORME 2:
SELECT
  (e.nombre_empleado || ' ' || e.apellido_paterno || ' ' || NVL(e.apellido_materno,'')) AS EMPLEADO,
  e.sueldo_base AS SUELDO,
  0.08 AS "POSIBLE AUMENTO",
  (e.sueldo_base * 1.08) AS "SALARIO SIMULADO"
FROM EMPLEADO e
WHERE e.sueldo_base BETWEEN 550000 AND 800000
ORDER BY e.sueldo_base ASC;

