
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

jdbc.driver=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://localhost:3306/Cine_DB?useSSL=false&serverTimezone=America/Santiago&useUnicode=true&characterEncoding=UTF-8
jdbc.user=Grupo6
jdbc.password=Grupo625
