# ===== BFF CAJERO (independiente) =====
spring.application.name=bff-cajero
server.port=8083

# ===== URL del servicio backend real (banco-servicios) =====
banco.servicios.url=http://localhost:9000

# ===== Logging =====
logging.level.com.bancoxyz.bffcajero=INFO
