-- DDL Oracle: Modelo para gestion de planta y turnos (MER-E -> Relacional)
-- Generado: 2025-10-12
SET DEFINE OFF;

-- -----------------------------
-- Tablas catalogo y secuencias
-- -----------------------------

CREATE TABLE region (
  id_region NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_region VARCHAR2(255) NOT NULL,
  CONSTRAINT region_un UNIQUE (nombre_region)
);

CREATE TABLE comuna (
  id_comuna NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_comuna VARCHAR2(100) NOT NULL,
  id_region NUMBER NOT NULL,
  CONSTRAINT comuna_fk_region FOREIGN KEY (id_region) REFERENCES region(id_region),
  CONSTRAINT comuna_un UNIQUE (nombre_comuna, id_region)
);

CREATE TABLE tipo_maquina (
  id_tipo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_tipo VARCHAR2(100) NOT NULL,
  CONSTRAINT tipo_maquina_un UNIQUE (nombre_tipo)
);

CREATE TABLE turno (
  id_turno NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_turno VARCHAR2(50) NOT NULL,
  entrada CHAR(5) NOT NULL, -- formato HH24:MI
  salida CHAR(5) NOT NULL,
  CONSTRAINT turno_un_nombre UNIQUE (nombre_turno),
  CONSTRAINT turno_ck_hora_entrada CHECK (REGEXP_LIKE(entrada,'^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$')),
  CONSTRAINT turno_ck_hora_salida CHECK (REGEXP_LIKE(salida,'^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$'))
);

-- -----------------------------
-- Plantas y maquinas
-- -----------------------------

CREATE TABLE planta (
  id_planta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_planta VARCHAR2(200) NOT NULL,
  direccion VARCHAR2(300) NOT NULL,
  id_comuna NUMBER NOT NULL,
  CONSTRAINT planta_fk_comuna FOREIGN KEY (id_comuna) REFERENCES comuna(id_comuna)
);

CREATE TABLE maquina (
  id_maquina NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  num_maquina NUMBER NOT NULL,
  id_planta NUMBER NOT NULL,
  nombre_maquina VARCHAR2(150),
  estado_activo CHAR(1) DEFAULT 'S' CHECK (estado_activo IN ('S','N')),
  id_tipo NUMBER NOT NULL,
  CONSTRAINT maquina_fk_planta FOREIGN KEY (id_planta) REFERENCES planta(id_planta),
  CONSTRAINT maquina_fk_tipo FOREIGN KEY (id_tipo) REFERENCES tipo_maquina(id_tipo),
  CONSTRAINT maquina_un UNIQUE (num_maquina, id_planta)
);

-- -----------------------------
-- Empleados (supertipo) y subtipos
-- -----------------------------

CREATE TABLE empleado (
  id_empleado NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rut VARCHAR2(12) NOT NULL UNIQUE,
  nombre VARCHAR2(100) NOT NULL,
  apellido_paterno VARCHAR2(100) NOT NULL,
  apellido_materno VARCHAR2(100),
  fecha_contratacion DATE,
  sueldo_base NUMBER(10,2),
  estado_activo CHAR(1) DEFAULT 'S' CHECK (estado_activo IN ('S','N')),
  id_planta NUMBER NOT NULL,
  id_afp NUMBER,
  id_salud NUMBER,
  id_jefe NUMBER,
  CONSTRAINT empleado_fk_planta FOREIGN KEY (id_planta) REFERENCES planta(id_planta),
  CONSTRAINT empleado_fk_jefe FOREIGN KEY (id_jefe) REFERENCES empleado(id_empleado)
);

CREATE TABLE jefe_turno (
  id_empleado NUMBER PRIMARY KEY,
  area_responsabilidad VARCHAR2(100),
  max_operarios NUMBER(3),
  CONSTRAINT jefe_turno_fk_emp FOREIGN KEY (id_empleado) REFERENCES empleado(id_empleado)
);

CREATE TABLE operario (
  id_empleado NUMBER PRIMARY KEY,
  categoria_proceso VARCHAR2(50),
  certificacion VARCHAR2(100),
  horas_turno NUMBER DEFAULT 8,
  CONSTRAINT operario_fk_emp FOREIGN KEY (id_empleado) REFERENCES empleado(id_empleado)
);

CREATE TABLE tecnico_mantencion (
  id_empleado NUMBER PRIMARY KEY,
  especialidad VARCHAR2(50),
  nivel_certificacion VARCHAR2(50),
  tiempo_respuesta NUMBER, -- en horas
  CONSTRAINT tecnico_fk_emp FOREIGN KEY (id_empleado) REFERENCES empleado(id_empleado)
);

-- -----------------------------
-- Mantenimiento y asignaciones
-- -----------------------------

CREATE TABLE orden_mantencion (
  id_orden NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_maquina NUMBER NOT NULL,
  id_tecnico NUMBER NOT NULL, -- FK a tecnico_mantencion.id_empleado
  fecha_programada DATE NOT NULL,
  fecha_ejecucion DATE,
  descripcion VARCHAR2(4000),
  CONSTRAINT orden_fk_maquina FOREIGN KEY (id_maquina) REFERENCES maquina(id_maquina),
  CONSTRAINT orden_fk_tecnico FOREIGN KEY (id_tecnico) REFERENCES tecnico_mantencion(id_empleado),
  CONSTRAINT orden_ck_fecha CHECK (fecha_ejecucion IS NULL OR fecha_ejecucion >= fecha_programada)
);

CREATE TABLE asignacion_turno (
  id_asignacion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_empleado NUMBER NOT NULL,
  id_turno NUMBER NOT NULL,
  id_maquina NUMBER,
  fecha_asignacion DATE NOT NULL,
  rol_en_turno VARCHAR2(100),
  CONSTRAINT asig_fk_emp FOREIGN KEY (id_empleado) REFERENCES empleado(id_empleado),
  CONSTRAINT asig_fk_turno FOREIGN KEY (id_turno) REFERENCES turno(id_turno),
  CONSTRAINT asig_unique_emp_fecha UNIQUE (id_empleado, fecha_asignacion)
);

-- -----------------------------
-- Indices recomendados para rendimiento
-- -----------------------------
CREATE INDEX ix_empleado_planta ON empleado(id_planta);
CREATE INDEX ix_maquina_planta ON maquina(id_planta);
CREATE INDEX ix_orden_maquina ON orden_mantencion(id_maquina);

COMMIT;

-- -----------------------------
-- Datos de ejemplo (inserts minimos requeridos para pruebas)
-- -----------------------------

/* REGIONES Y COMUNAS */
INSERT INTO region(nombre_region) VALUES('Region Metropolitana');
INSERT INTO region(nombre_region) VALUES('Region de Valparaiso');

INSERT INTO comuna(nombre_comuna, id_region) VALUES('Santiago', 1);
INSERT INTO comuna(nombre_comuna, id_region) VALUES('Maipu', 1);
INSERT INTO comuna(nombre_comuna, id_region) VALUES('Valparaiso', 2);

-- TIPOS MAQUINA Y TURNOS
INSERT INTO tipo_maquina(nombre_tipo) VALUES('Cortadora');
INSERT INTO tipo_maquina(nombre_tipo) VALUES('Pulidora');

INSERT INTO turno(nombre_turno, entrada, salida) VALUES('Manana','06:00','14:00');
INSERT INTO turno(nombre_turno, entrada, salida) VALUES('Tarde','14:00','22:00');
INSERT INTO turno(nombre_turno, entrada, salida) VALUES('Noche','22:00','06:00');

-- PLANTAS
INSERT INTO planta(nombre_planta, direccion, id_comuna) VALUES('Planta Norte','Av. Industrial 100', 1);
INSERT INTO planta(nombre_planta, direccion, id_comuna) VALUES('Planta Sur','Camino Real 200', 2);

-- MAQUINAS
INSERT INTO maquina(num_maquina, id_planta, nombre_maquina, id_tipo) VALUES(1,1,'Cortadora A',1);
INSERT INTO maquina(num_maquina, id_planta, nombre_maquina, id_tipo) VALUES(2,1,'Pulidora B',2);
INSERT INTO maquina(num_maquina, id_planta, nombre_maquina, id_tipo) VALUES(1,2,'Cortadora C',1);

-- EMPLEADOS (supertipo)
INSERT INTO empleado(rut,nombre,apellido_paterno,apellido_materno,fecha_contratacion,sueldo_base,id_planta)
VALUES('11.111.111-1','Carlos','Gomez','Rojas',TO_DATE('2019-02-01','YYYY-MM-DD'),550000,1);
INSERT INTO empleado(rut,nombre,apellido_paterno,apellido_materno,fecha_contratacion,sueldo_base,id_planta)
VALUES('22.222.222-2','Maria','Perez','Lopez',TO_DATE('2018-06-15','YYYY-MM-DD'),650000,1);
INSERT INTO empleado(rut,nombre,apellido_paterno,apellido_materno,fecha_contratacion,sueldo_base,id_planta,id_jefe)
VALUES('33.333.333-3','Pedro','Sanchez','Munoz',TO_DATE('2020-03-10','YYYY-MM-DD'),480000,2,1);

-- Subtipos: asignar roles
-- Asumimos los id_empleado generados automaticamente en orden (1,2,3) - si tu BD genera otros, ajusta
INSERT INTO jefe_turno(id_empleado, area_responsabilidad, max_operarios) VALUES(1,'Linea A',10);
INSERT INTO tecnico_mantencion(id_empleado, especialidad, nivel_certificacion, tiempo_respuesta) VALUES(2,'Electromecanica','Nivel 2',4);
INSERT INTO operario(id_empleado, categoria_proceso, certificacion, horas_turno) VALUES(3,'Corte','Certificado A',8);

-- ORDENES DE MANTENCION
INSERT INTO orden_mantencion(id_maquina,id_tecnico,fecha_programada,descripcion)
VALUES(1,2,TO_DATE('2025-10-01','YYYY-MM-DD'),'Revision preventiva - faja de corte');

-- ASIGNACIONES DE TURNO
INSERT INTO asignacion_turno(id_empleado,id_turno,id_maquina,fecha_asignacion,rol_en_turno)
VALUES(1,1,1,TO_DATE('2025-10-01','YYYY-MM-DD'),'Jefe de Linea');
INSERT INTO asignacion_turno(id_empleado,id_turno,id_maquina,fecha_asignacion,rol_en_turno)
VALUES(3,1,1,TO_DATE('2025-10-01','YYYY-MM-DD'),'Operador Corte');

COMMIT;

-- -----------------------------
-- Consultas solicitadas (INFORME 1 y 2)
-- -----------------------------

-- INFORME 1: Turnos con entrada posterior a 20:00 (orden descendente por entrada)
SELECT nombre_turno AS turno, entrada, salida
FROM turno
WHERE entrada > '20:00'
ORDER BY entrada DESC;

-- INFORME 2: Turnos diurnos con entrada entre 06:00 y 14:59 (orden ascendente)
SELECT nombre_turno AS turno, entrada, salida
FROM turno
WHERE entrada BETWEEN '06:00' AND '14:59'
ORDER BY entrada ASC;