# ===== Aplicacion BFF Banco XYZ =====
spring.application.name=bff-bancoxyz
server.port=8080

# ===== Base de datos H2 (desarrollo) =====
spring.datasource.url=jdbc:h2:mem:bancoxyz;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===== JPA =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# ===== Logging =====
logging.level.com.bancoxyz.bff=INFO
