server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    # El servidor Eureka no se registra a si mismo ni busca pares.
    register-with-eureka: false
    fetch-registry: false
  server:
    # Deshabilita el modo de autoproteccion para entorno de desarrollo.
    enable-self-preservation: false
