-- Configuración de sesión
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE; 
ALTER SESSION SET NLS_DATE_FORMAT='DD/MM/YYYY';

/*************************************************************************
  BLOQUE 1: ESTRATEGIA DE SEGURIDAD
  EJECUTAR CON: SYSTEM o ADMIN
  OBJETIVO: Crear roles, usuarios y asignar permisos base.
**************************************************************************/

-- 1.1 Creación de Roles (Tabla 3)
CREATE ROLE PRY2205_ROL_D; -- Rol Desarrollador
GRANT CREATE SESSION, CREATE VIEW, CREATE TABLE TO PRY2205_ROL_D;
GRANT UNLIMITED TABLESPACE TO PRY2205_ROL_D;

CREATE ROLE PRY2205_ROL_C; -- Rol Consultor
GRANT CREATE SESSION TO PRY2205_ROL_C;

-- 1.2 Creación de Usuarios (Tabla 1)
-- Usuario Dueño (Owner)
CREATE USER PRY2205_EFT IDENTIFIED BY "Pry2024.Owner"
DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

-- Usuario Desarrollador
CREATE USER PRY2205_EFT_DES IDENTIFIED BY "Pry2024.Dev"
DEFAULT TABLESPACE USERS QUOTA 10M ON USERS;

-- Usuario Consultor
CREATE USER PRY2205_EFT_CON IDENTIFIED BY "Pry2024.Cons"
DEFAULT TABLESPACE USERS QUOTA 10M ON USERS;

-- 1.3 Asignación de Roles y Permisos
GRANT PRY2205_ROL_D TO PRY2205_EFT_DES;
GRANT PRY2205_ROL_C TO PRY2205_EFT_CON;

-- Permisos especiales para el Owner (Dueño del esquema)
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE SYNONYM, CREATE PUBLIC SYNONYM TO PRY2205_EFT;


/*************************************************************************
  BLOQUE 2: CONFIGURACIÓN DEL ESQUEMA Y SINÓNIMOS
  EJECUTAR CON: PRY2205_EFT (Usuario Dueño)
**************************************************************************/

-- [IMPORTANTE]
-- AQUÍ EJECUTAR EL SCRIPT: "PRY2205_EFT_S9_CreaEsquemaPoblado.sql"

-- 2.1 Sinónimos Públicos (Estrategia de Nombres Alternativos)
CREATE OR REPLACE PUBLIC SYNONYM PROFESIONAL FOR PRY2205_EFT.PROFESIONAL;
CREATE OR REPLACE PUBLIC SYNONYM PROFESION FOR PRY2205_EFT.PROFESION;
CREATE OR REPLACE PUBLIC SYNONYM ISAPRE FOR PRY2205_EFT.ISAPRE;
CREATE OR REPLACE PUBLIC SYNONYM TIPO_CONTRATO FOR PRY2205_EFT.TIPO_CONTRATO;
CREATE OR REPLACE PUBLIC SYNONYM RANGOS_SUELDOS FOR PRY2205_EFT.RANGOS_SUELDOS;
CREATE OR REPLACE PUBLIC SYNONYM EMPRESA FOR PRY2205_EFT.EMPRESA;
CREATE OR REPLACE PUBLIC SYNONYM ASESORIA FOR PRY2205_EFT.ASESORIA;

-- 2.2 Sinónimos Privados (Uso interno)
CREATE OR REPLACE SYNONYM L_EMPRESA FOR EMPRESA;
CREATE OR REPLACE SYNONYM L_ASESORIA FOR ASESORIA;

-- 2.3 Asignación de Privilegios (Principio de Menor Privilegio)
-- Se otorga SELECT solo al Rol de Desarrollador
GRANT SELECT ON PROFESIONAL TO PRY2205_ROL_D;
GRANT SELECT ON PROFESION TO PRY2205_ROL_D;
GRANT SELECT ON ISAPRE TO PRY2205_ROL_D;
GRANT SELECT ON TIPO_CONTRATO TO PRY2205_ROL_D;
GRANT SELECT ON RANGOS_SUELDOS TO PRY2205_ROL_D;
GRANT SELECT ON EMPRESA TO PRY2205_ROL_D;
GRANT SELECT ON ASESORIA TO PRY2205_ROL_D;


/*************************************************************************
  BLOQUE 3: CASO 2 - INFORME REMUNERACIONES (CARTOLA)
  EJECUTAR CON: PRY2205_EFT_DES (Usuario Desarrollador)
**************************************************************************/

-- 3.1 Creación de Tabla CARTOLA_PROFESIONALES
-- Lógica: Join No-Equitativo para rangos de sueldo y CASE para movilización.
CREATE TABLE CARTOLA_PROFESIONALES AS
SELECT 
    p.RUTPROF AS "RUT PROFESIONAL",
    INITCAP(p.NOMPRO || ' ' || p.APPPRO || ' ' || p.APMPRO) AS "NOMBRE COMPLETO",
    UPPER(pr.NOMPROFESION) AS "PROFESION",
    i.NOMISAPRE AS "ISAPRE",
    p.SUELDO AS "SUELDO BASE",
    
    -- Comisión (BD tiene decimales ej: 0.05)
    NVL(p.COMISION, 0) AS "PORCENTAJE COMISION",
    ROUND(p.SUELDO * NVL(p.COMISION, 0)) AS "VALOR COMISION",
    
    -- Honorarios (Desde tabla RANGOS_SUELDOS)
    rs.HONOR_PCT AS "PORCENTAJE HONORARIOS",
    ROUND(p.SUELDO * (rs.HONOR_PCT / 100)) AS "VALOR HONORARIOS",
    
    -- Bono Movilización según contrato
    CASE 
        WHEN UPPER(tc.NOMTCONTRATO) LIKE '%INDEFINIDO JORNADA COMPLETA%' THEN 150000
        WHEN UPPER(tc.NOMTCONTRATO) LIKE '%INDEFINIDO JORNADA PARCIAL%' THEN 120000
        WHEN UPPER(tc.NOMTCONTRATO) LIKE '%PLAZO FIJO%' THEN 60000
        WHEN UPPER(tc.NOMTCONTRATO) LIKE '%HONORARIOS%' THEN 50000
        ELSE 0
    END AS "BONO MOVILIZACION",
    
    -- Total a Pagar
    ROUND(
        p.SUELDO + 
        (p.SUELDO * NVL(p.COMISION, 0)) + 
        (p.SUELDO * (rs.HONOR_PCT / 100)) + 
        CASE 
            WHEN UPPER(tc.NOMTCONTRATO) LIKE '%INDEFINIDO JORNADA COMPLETA%' THEN 150000
            WHEN UPPER(tc.NOMTCONTRATO) LIKE '%INDEFINIDO JORNADA PARCIAL%' THEN 120000
            WHEN UPPER(tc.NOMTCONTRATO) LIKE '%PLAZO FIJO%' THEN 60000
            WHEN UPPER(tc.NOMTCONTRATO) LIKE '%HONORARIOS%' THEN 50000
            ELSE 0
        END
    ) AS "TOTAL A PAGAR"
FROM 
    PROFESIONAL p
    JOIN PROFESION pr ON p.IDPROFESION = pr.IDPROFESION
    JOIN ISAPRE i ON p.IDISAPRE = i.IDISAPRE
    JOIN TIPO_CONTRATO tc ON p.IDTCONTRATO = tc.IDTCONTRATO
    JOIN RANGOS_SUELDOS rs ON p.SUELDO BETWEEN rs.S_MIN AND rs.S_MAX
ORDER BY 
    "PROFESION" ASC, "SUELDO BASE" DESC, "PORCENTAJE COMISION" ASC, "RUT PROFESIONAL" ASC;

-- 3.2 Otorgar permisos al Consultor
GRANT SELECT ON CARTOLA_PROFESIONALES TO PRY2205_EFT_CON;


/*************************************************************************
  BLOQUE 4: CASO 3 - VISTAS Y OPTIMIZACIÓN
  EJECUTAR CON: PRY2205_EFT (Usuario Dueño)
**************************************************************************/

-- 4.1 Creación de Vista VW_EMPRESAS_ASESORADAS
-- Lógica: Filtro paramétrico (Año actual - 1) usando la columna 'FIN'
CREATE OR REPLACE VIEW VW_EMPRESAS_ASESORADAS AS
SELECT 
    e.RUT_EMPRESA || '-' || e.DV_EMPRESA AS "RUT EMPRESA",
    e.NOMEMPRESA AS "NOMBRE EMPRESA",
    TRUNC(MONTHS_BETWEEN(SYSDATE, e.FECHA_INICIACION_ACTIVIDADES)/12) AS "AÑOS ANTIGUEDAD",
    TO_CHAR(e.IVA_DECLARADO, '$999G999G999') AS "IVA DECLARADO",
    
    COUNT(*) AS "TOTAL ASESORIAS ANUAL",
    ROUND(COUNT(*) / 12) AS "ASESORIAS PROMEDIO MENSUAL",
    TO_CHAR(ROUND(e.IVA_DECLARADO * (ROUND(COUNT(*) / 12) / 100)), '$999G999G999') AS "DEVOLUCION IVA ESTIMADA",
    
    -- Categorización Cliente
    CASE 
        WHEN ROUND(COUNT(*) / 12) > 5 THEN 'CLIENTE PREMIUM'
        WHEN ROUND(COUNT(*) / 12) BETWEEN 3 AND 5 THEN 'CLIENTE'
        ELSE 'CLIENTE POCO CONCURRIDO'
    END AS "TIPO CLIENTE",
    
    -- Promociones (Case Anidado)
    CASE 
        WHEN ROUND(COUNT(*) / 12) > 5 THEN
            CASE WHEN COUNT(*) >= 7 THEN '1 ASESORÍA GRATIS' ELSE '1 ASESORÍA 40% DE DESCUENTO' END
        WHEN ROUND(COUNT(*) / 12) BETWEEN 3 AND 5 THEN
            CASE WHEN COUNT(*) = 5 THEN '1 ASESORÍA 30% DE DESCUENTO' ELSE '1 ASESORÍA 20% DE DESCUENTO' END
        ELSE 'CAPTAR CLIENTE'
    END AS "PROMOCION SUGERIDA"
FROM 
    L_EMPRESA e
    JOIN L_ASESORIA a ON e.IDEMPRESA = a.IDEMPRESA
WHERE 
    EXTRACT(YEAR FROM a.FIN) = EXTRACT(YEAR FROM SYSDATE) - 1
GROUP BY 
    e.RUT_EMPRESA, e.DV_EMPRESA, e.NOMEMPRESA, e.FECHA_INICIACION_ACTIVIDADES, e.IVA_DECLARADO
ORDER BY 
    "NOMBRE EMPRESA" ASC;

-- 4.2 Otorgar permisos al Consultor
GRANT SELECT ON VW_EMPRESAS_ASESORADAS TO PRY2205_EFT_CON;

-- 4.3 Optimización (Caso 3.2): Creación de Índices
CREATE INDEX IDX_ASESORIA_FIN_YEAR ON ASESORIA(EXTRACT(YEAR FROM FIN));
CREATE INDEX IDX_ASESORIA_EMPRESA_FK ON ASESORIA(IDEMPRESA);


/*************************************************************************
  BLOQUE 5: VERIFICACIÓN FINAL
  EJECUTAR CON: PRY2205_EFT_CON (Usuario Consultor)
**************************************************************************/

SELECT * FROM PRY2205_EFT_DES.CARTOLA_PROFESIONALES;
SELECT * FROM PRY2205_EFT.VW_EMPRESAS_ASESORADAS;