-- Generado por Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   en:        2025-09-14 19:01:52 CLST
--   sitio:      Oracle Database 21c
--   tipo:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE afp (
    id_afp     NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY ( START WITH 1 NOCACHE )
    NOT NULL,
    codigo_afp VARCHAR2(10),
    nombre_afp VARCHAR2(80) NOT NULL
)
LOGGING;

ALTER TABLE afp ADD CONSTRAINT afp_pk PRIMARY KEY ( id_afp );

ALTER TABLE afp ADD CONSTRAINT index_1 UNIQUE ( codigo_afp );


CREATE TABLE AFP_JN
 (JN_OPERATION CHAR(3) NOT NULL
 ,JN_ORACLE_USER VARCHAR2(30) NOT NULL
 ,JN_DATETIME DATE NOT NULL
 ,JN_NOTES VARCHAR2(240)
 ,JN_APPLN VARCHAR2(35)
 ,JN_SESSION NUMBER(38)
 ,id_afp NUMBER NOT NULL
 ,codigo_afp VARCHAR2 (10)
 ,nombre_afp VARCHAR2 (80) NOT NULL
 );

CREATE OR REPLACE TRIGGER AFP_JNtrg
  AFTER 
  INSERT OR 
  UPDATE OR 
  DELETE ON AFP for each row 
 Declare 
  rec AFP_JN%ROWTYPE; 
  blank AFP_JN%ROWTYPE; 
  BEGIN 
    rec := blank; 
    IF INSERTING OR UPDATING THEN 
      rec.id_afp := :NEW.id_afp; 
      rec.codigo_afp := :NEW.codigo_afp; 
      rec.nombre_afp := :NEW.nombre_afp; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      IF INSERTING THEN 
        rec.JN_OPERATION := 'INS'; 
      ELSIF UPDATING THEN 
        rec.JN_OPERATION := 'UPD'; 
      END IF; 
    ELSIF DELETING THEN 
      rec.id_afp := :OLD.id_afp; 
      rec.codigo_afp := :OLD.codigo_afp; 
      rec.nombre_afp := :OLD.nombre_afp; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      rec.JN_OPERATION := 'DEL'; 
    END IF; 
    INSERT into AFP_JN VALUES rec; 
  END; 
  /CREATE TABLE atencion (
    id_atencion     NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY ( START WITH 1 NOCACHE )
    NOT NULL,
    fecha_hora      TIMESTAMP NOT NULL,
    tipo_atencion   VARCHAR2(20) NOT NULL,
    rut_paciente    VARCHAR2(12) NOT NULL,
    rut_medico      VARCHAR2(12) NOT NULL,
    id_especialidad NUMBER NOT NULL,
    diagnostico     VARCHAR2(4000),
    observaciones   VARCHAR2(1000)
)
LOGGING;

CREATE INDEX ix_atencion_paciente ON
    atencion (
        rut_paciente
    ASC );

CREATE INDEX ix_atencion_medico ON
    atencion (
        rut_medico
    ASC );

ALTER TABLE atencion ADD CONSTRAINT atencion_pk PRIMARY KEY ( id_atencion );


CREATE TABLE ATENCION_JN
 (JN_OPERATION CHAR(3) NOT NULL
 ,JN_ORACLE_USER VARCHAR2(30) NOT NULL
 ,JN_DATETIME DATE NOT NULL
 ,JN_NOTES VARCHAR2(240)
 ,JN_APPLN VARCHAR2(35)
 ,JN_SESSION NUMBER(38)
 ,id_atencion NUMBER NOT NULL
 ,fecha_hora TIMESTAMP NOT NULL
 ,tipo_atencion VARCHAR2 (20) NOT NULL
 ,rut_paciente VARCHAR2 (12) NOT NULL
 ,rut_medico VARCHAR2 (12) NOT NULL
 ,id_especialidad NUMBER NOT NULL
 ,diagnostico VARCHAR2 (4000)
 ,observaciones VARCHAR2 (1000)
 );

CREATE OR REPLACE TRIGGER ATENCION_JNtrg
  AFTER 
  INSERT OR 
  UPDATE OR 
  DELETE ON ATENCION for each row 
 Declare 
  rec ATENCION_JN%ROWTYPE; 
  blank ATENCION_JN%ROWTYPE; 
  BEGIN 
    rec := blank; 
    IF INSERTING OR UPDATING THEN 
      rec.id_atencion := :NEW.id_atencion; 
      rec.fecha_hora := :NEW.fecha_hora; 
      rec.tipo_atencion := :NEW.tipo_atencion; 
      rec.rut_paciente := :NEW.rut_paciente; 
      rec.rut_medico := :NEW.rut_medico; 
      rec.id_especialidad := :NEW.id_especialidad; 
      rec.diagnostico := :NEW.diagnostico; 
      rec.observaciones := :NEW.observaciones; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      IF INSERTING THEN 
        rec.JN_OPERATION := 'INS'; 
      ELSIF UPDATING THEN 
        rec.JN_OPERATION := 'UPD'; 
      END IF; 
    ELSIF DELETING THEN 
      rec.id_atencion := :OLD.id_atencion; 
      rec.fecha_hora := :OLD.fecha_hora; 
      rec.tipo_atencion := :OLD.tipo_atencion; 
      rec.rut_paciente := :OLD.rut_paciente; 
      rec.rut_medico := :OLD.rut_medico; 
      rec.id_especialidad := :OLD.id_especialidad; 
      rec.diagnostico := :OLD.diagnostico; 
      rec.observaciones := :OLD.observaciones; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      rec.JN_OPERATION := 'DEL'; 
    END IF; 
    INSERT into ATENCION_JN VALUES rec; 
  END; 
  /CREATE TABLE comuna (
    id_comuna     NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY ( START WITH 1 NOCACHE )
    NOT NULL,
    nombre_comuna VARCHAR2(60) NOT NULL,
    id_region     NUMBER NOT NULL
)
LOGGING;

ALTER TABLE comuna ADD CONSTRAINT comuna_pk PRIMARY KEY ( id_comuna );


CREATE TABLE COMUNA_JN
 (JN_OPERATION CHAR(3) NOT NULL
 ,JN_ORACLE_USER VARCHAR2(30) NOT NULL
 ,JN_DATETIME DATE NOT NULL
 ,JN_NOTES VARCHAR2(240)
 ,JN_APPLN VARCHAR2(35)
 ,JN_SESSION NUMBER(38)
 ,id_comuna NUMBER NOT NULL
 ,nombre_comuna VARCHAR2 (60) NOT NULL
 ,id_region NUMBER NOT NULL
 );

CREATE OR REPLACE TRIGGER COMUNA_JNtrg
  AFTER 
  INSERT OR 
  UPDATE OR 
  DELETE ON COMUNA for each row 
 Declare 
  rec COMUNA_JN%ROWTYPE; 
  blank COMUNA_JN%ROWTYPE; 
  BEGIN 
    rec := blank; 
    IF INSERTING OR UPDATING THEN 
      rec.id_comuna := :NEW.id_comuna; 
      rec.nombre_comuna := :NEW.nombre_comuna; 
      rec.id_region := :NEW.id_region; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      IF INSERTING THEN 
        rec.JN_OPERATION := 'INS'; 
      ELSIF UPDATING THEN 
        rec.JN_OPERATION := 'UPD'; 
      END IF; 
    ELSIF DELETING THEN 
      rec.id_comuna := :OLD.id_comuna; 
      rec.nombre_comuna := :OLD.nombre_comuna; 
      rec.id_region := :OLD.id_region; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      rec.JN_OPERATION := 'DEL'; 
    END IF; 
    INSERT into COMUNA_JN VALUES rec; 
  END; 
  /CREATE TABLE especialidad (
    id_especialidad     NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY ( START WITH 1 NOCACHE )
    NOT NULL,
    nombre_especialidad VARCHAR2(80) NOT NULL
)
LOGGING;

ALTER TABLE especialidad ADD CONSTRAINT especialidad_pk PRIMARY KEY ( id_especialidad );


CREATE TABLE ESPECIALIDAD_JN
 (JN_OPERATION CHAR(3) NOT NULL
 ,JN_ORACLE_USER VARCHAR2(30) NOT NULL
 ,JN_DATETIME DATE NOT NULL
 ,JN_NOTES VARCHAR2(240)
 ,JN_APPLN VARCHAR2(35)
 ,JN_SESSION NUMBER(38)
 ,id_especialidad NUMBER NOT NULL
 ,nombre_especialidad VARCHAR2 (80) NOT NULL
 );

CREATE OR REPLACE TRIGGER ESPECIALIDAD_JNtrg
  AFTER 
  INSERT OR 
  UPDATE OR 
  DELETE ON ESPECIALIDAD for each row 
 Declare 
  rec ESPECIALIDAD_JN%ROWTYPE; 
  blank ESPECIALIDAD_JN%ROWTYPE; 
  BEGIN 
    rec := blank; 
    IF INSERTING OR UPDATING THEN 
      rec.id_especialidad := :NEW.id_especialidad; 
      rec.nombre_especialidad := :NEW.nombre_especialidad; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      IF INSERTING THEN 
        rec.JN_OPERATION := 'INS'; 
      ELSIF UPDATING THEN 
        rec.JN_OPERATION := 'UPD'; 
      END IF; 
    ELSIF DELETING THEN 
      rec.id_especialidad := :OLD.id_especialidad; 
      rec.nombre_especialidad := :OLD.nombre_especialidad; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      rec.JN_OPERATION := 'DEL'; 
    END IF; 
    INSERT into ESPECIALIDAD_JN VALUES rec; 
  END; 
  /CREATE TABLE examen (
    id_examen               NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY ( START WITH 1 NOCACHE )
    NOT NULL,
    codigo_examen           VARCHAR2(20) NOT NULL,
    nombre_examen           VARCHAR2(120) NOT NULL,
    tipo_muestra            VARCHAR2(80) NOT NULL,
    condiciones_preparacion VARCHAR2(200)
)
LOGGING;

ALTER TABLE examen ADD CONSTRAINT examen_pk PRIMARY KEY ( id_examen );

ALTER TABLE examen ADD CONSTRAINT index_1 UNIQUE ( codigo_examen );


CREATE TABLE EXAMEN_JN
 (JN_OPERATION CHAR(3) NOT NULL
 ,JN_ORACLE_USER VARCHAR2(30) NOT NULL
 ,JN_DATETIME DATE NOT NULL
 ,JN_NOTES VARCHAR2(240)
 ,JN_APPLN VARCHAR2(35)
 ,JN_SESSION NUMBER(38)
 ,id_examen NUMBER NOT NULL
 ,codigo_examen VARCHAR2 (20) NOT NULL
 ,nombre_examen VARCHAR2 (120) NOT NULL
 ,tipo_muestra VARCHAR2 (80) NOT NULL
 ,condiciones_preparacion VARCHAR2 (200)
 );

CREATE OR REPLACE TRIGGER EXAMEN_JNtrg
  AFTER 
  INSERT OR 
  UPDATE OR 
  DELETE ON EXAMEN for each row 
 Declare 
  rec EXAMEN_JN%ROWTYPE; 
  blank EXAMEN_JN%ROWTYPE; 
  BEGIN 
    rec := blank; 
    IF INSERTING OR UPDATING THEN 
      rec.id_examen := :NEW.id_examen; 
      rec.codigo_examen := :NEW.codigo_examen; 
      rec.nombre_examen := :NEW.nombre_examen; 
      rec.tipo_muestra := :NEW.tipo_muestra; 
      rec.condiciones_preparacion := :NEW.condiciones_preparacion; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      IF INSERTING THEN 
        rec.JN_OPERATION := 'INS'; 
      ELSIF UPDATING THEN 
        rec.JN_OPERATION := 'UPD'; 
      END IF; 
    ELSIF DELETING THEN 
      rec.id_examen := :OLD.id_examen; 
      rec.codigo_examen := :OLD.codigo_examen; 
      rec.nombre_examen := :OLD.nombre_examen; 
      rec.tipo_muestra := :OLD.tipo_muestra; 
      rec.condiciones_preparacion := :OLD.condiciones_preparacion; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      rec.JN_OPERATION := 'DEL'; 
    END IF; 
    INSERT into EXAMEN_JN VALUES rec; 
  END; 
  /CREATE TABLE institucion_salud (
    id_institucion_salud NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY ( START WITH 1 NOCACHE )
    NOT NULL,
    codigo               VARCHAR2(10),
    nombre               VARCHAR2(80) NOT NULL,
    tipo                 VARCHAR2(10) NOT NULL
)
LOGGING;

ALTER TABLE institucion_salud ADD CONSTRAINT institucion_salud_pk PRIMARY KEY ( id_institucion_salud );

ALTER TABLE institucion_salud ADD CONSTRAINT index_1 UNIQUE ( codigo );


CREATE TABLE INSTITUCION_SALUD_JN
 (JN_OPERATION CHAR(3) NOT NULL
 ,JN_ORACLE_USER VARCHAR2(30) NOT NULL
 ,JN_DATETIME DATE NOT NULL
 ,JN_NOTES VARCHAR2(240)
 ,JN_APPLN VARCHAR2(35)
 ,JN_SESSION NUMBER(38)
 ,id_institucion_salud NUMBER NOT NULL
 ,codigo VARCHAR2 (10)
 ,nombre VARCHAR2 (80) NOT NULL
 ,tipo VARCHAR2 (10) NOT NULL
 );

CREATE OR REPLACE TRIGGER INSTITUCION_SALUD_JNtrg
  AFTER 
  INSERT OR 
  UPDATE OR 
  DELETE ON INSTITUCION_SALUD for each row 
 Declare 
  rec INSTITUCION_SALUD_JN%ROWTYPE; 
  blank INSTITUCION_SALUD_JN%ROWTYPE; 
  BEGIN 
    rec := blank; 
    IF INSERTING OR UPDATING THEN 
      rec.id_institucion_salud := :NEW.id_institucion_salud; 
      rec.codigo := :NEW.codigo; 
      rec.nombre := :NEW.nombre; 
      rec.tipo := :NEW.tipo; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      IF INSERTING THEN 
        rec.JN_OPERATION := 'INS'; 
      ELSIF UPDATING THEN 
        rec.JN_OPERATION := 'UPD'; 
      END IF; 
    ELSIF DELETING THEN 
      rec.id_institucion_salud := :OLD.id_institucion_salud; 
      rec.codigo := :OLD.codigo; 
      rec.nombre := :OLD.nombre; 
      rec.tipo := :OLD.tipo; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      rec.JN_OPERATION := 'DEL'; 
    END IF; 
    INSERT into INSTITUCION_SALUD_JN VALUES rec; 
  END; 
  /CREATE TABLE medico (
    rut_medico           VARCHAR2(12) NOT NULL,
    nombre_completo      VARCHAR2(100) NOT NULL,
    fecha_ingreso        DATE NOT NULL,
    id_especialidad      NUMBER NOT NULL,
    id_afp               NUMBER,
    id_institucion_salud NUMBER,
    rut_supervisor       VARCHAR2(12)
)
LOGGING;

ALTER TABLE medico ADD CONSTRAINT medico_pk PRIMARY KEY ( rut_medico );


CREATE TABLE MEDICO_JN
 (JN_OPERATION CHAR(3) NOT NULL
 ,JN_ORACLE_USER VARCHAR2(30) NOT NULL
 ,JN_DATETIME DATE NOT NULL
 ,JN_NOTES VARCHAR2(240)
 ,JN_APPLN VARCHAR2(35)
 ,JN_SESSION NUMBER(38)
 ,rut_medico VARCHAR2 (12) NOT NULL
 ,nombre_completo VARCHAR2 (100) NOT NULL
 ,fecha_ingreso DATE NOT NULL
 ,id_especialidad NUMBER NOT NULL
 ,id_afp NUMBER
 ,id_institucion_salud NUMBER
 ,rut_supervisor VARCHAR2 (12)
 );

CREATE OR REPLACE TRIGGER MEDICO_JNtrg
  AFTER 
  INSERT OR 
  UPDATE OR 
  DELETE ON MEDICO for each row 
 Declare 
  rec MEDICO_JN%ROWTYPE; 
  blank MEDICO_JN%ROWTYPE; 
  BEGIN 
    rec := blank; 
    IF INSERTING OR UPDATING THEN 
      rec.rut_medico := :NEW.rut_medico; 
      rec.nombre_completo := :NEW.nombre_completo; 
      rec.fecha_ingreso := :NEW.fecha_ingreso; 
      rec.id_especialidad := :NEW.id_especialidad; 
      rec.id_afp := :NEW.id_afp; 
      rec.id_institucion_salud := :NEW.id_institucion_salud; 
      rec.rut_supervisor := :NEW.rut_supervisor; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      IF INSERTING THEN 
        rec.JN_OPERATION := 'INS'; 
      ELSIF UPDATING THEN 
        rec.JN_OPERATION := 'UPD'; 
      END IF; 
    ELSIF DELETING THEN 
      rec.rut_medico := :OLD.rut_medico; 
      rec.nombre_completo := :OLD.nombre_completo; 
      rec.fecha_ingreso := :OLD.fecha_ingreso; 
      rec.id_especialidad := :OLD.id_especialidad; 
      rec.id_afp := :OLD.id_afp; 
      rec.id_institucion_salud := :OLD.id_institucion_salud; 
      rec.rut_supervisor := :OLD.rut_supervisor; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      rec.JN_OPERATION := 'DEL'; 
    END IF; 
    INSERT into MEDICO_JN VALUES rec; 
  END; 
  /CREATE TABLE paciente (
    rut_paciente     VARCHAR2(12) NOT NULL,
    nombre_completo  VARCHAR2(100) NOT NULL,
    sexo             CHAR(1) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    direccion        VARCHAR2(150) NOT NULL,
    id_comuna        NUMBER NOT NULL,
    tipo_usuario     VARCHAR2(15) NOT NULL
)
LOGGING;

CREATE INDEX ix_paciente_comuna ON
    paciente (
        id_comuna
    ASC );

ALTER TABLE paciente ADD CONSTRAINT paciente_pk PRIMARY KEY ( rut_paciente );


CREATE TABLE PACIENTE_JN
 (JN_OPERATION CHAR(3) NOT NULL
 ,JN_ORACLE_USER VARCHAR2(30) NOT NULL
 ,JN_DATETIME DATE NOT NULL
 ,JN_NOTES VARCHAR2(240)
 ,JN_APPLN VARCHAR2(35)
 ,JN_SESSION NUMBER(38)
 ,rut_paciente VARCHAR2 (12) NOT NULL
 ,nombre_completo VARCHAR2 (100) NOT NULL
 ,sexo CHAR (1) NOT NULL
 ,fecha_nacimiento DATE NOT NULL
 ,direccion VARCHAR2 (150) NOT NULL
 ,id_comuna NUMBER NOT NULL
 ,tipo_usuario VARCHAR2 (15) NOT NULL
 );

CREATE OR REPLACE TRIGGER PACIENTE_JNtrg
  AFTER 
  INSERT OR 
  UPDATE OR 
  DELETE ON PACIENTE for each row 
 Declare 
  rec PACIENTE_JN%ROWTYPE; 
  blank PACIENTE_JN%ROWTYPE; 
  BEGIN 
    rec := blank; 
    IF INSERTING OR UPDATING THEN 
      rec.rut_paciente := :NEW.rut_paciente; 
      rec.nombre_completo := :NEW.nombre_completo; 
      rec.sexo := :NEW.sexo; 
      rec.fecha_nacimiento := :NEW.fecha_nacimiento; 
      rec.direccion := :NEW.direccion; 
      rec.id_comuna := :NEW.id_comuna; 
      rec.tipo_usuario := :NEW.tipo_usuario; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      IF INSERTING THEN 
        rec.JN_OPERATION := 'INS'; 
      ELSIF UPDATING THEN 
        rec.JN_OPERATION := 'UPD'; 
      END IF; 
    ELSIF DELETING THEN 
      rec.rut_paciente := :OLD.rut_paciente; 
      rec.nombre_completo := :OLD.nombre_completo; 
      rec.sexo := :OLD.sexo; 
      rec.fecha_nacimiento := :OLD.fecha_nacimiento; 
      rec.direccion := :OLD.direccion; 
      rec.id_comuna := :OLD.id_comuna; 
      rec.tipo_usuario := :OLD.tipo_usuario; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      rec.JN_OPERATION := 'DEL'; 
    END IF; 
    INSERT into PACIENTE_JN VALUES rec; 
  END; 
  /CREATE TABLE pago (
    id_pago     NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY ( START WITH 1 NOCACHE )
    NOT NULL,
    id_atencion NUMBER NOT NULL,
    monto       NUMBER(12, 2) NOT NULL,
    tipo_pago   VARCHAR2(20) NOT NULL,
    fecha_pago  DATE NOT NULL
)
LOGGING;

ALTER TABLE pago ADD CONSTRAINT pago_pk PRIMARY KEY ( id_pago );

ALTER TABLE pago ADD CONSTRAINT uk_pago_atencion UNIQUE ( id_atencion );


CREATE TABLE PAGO_JN
 (JN_OPERATION CHAR(3) NOT NULL
 ,JN_ORACLE_USER VARCHAR2(30) NOT NULL
 ,JN_DATETIME DATE NOT NULL
 ,JN_NOTES VARCHAR2(240)
 ,JN_APPLN VARCHAR2(35)
 ,JN_SESSION NUMBER(38)
 ,id_pago NUMBER NOT NULL
 ,id_atencion NUMBER NOT NULL
 ,monto NUMBER (12,2) NOT NULL
 ,tipo_pago VARCHAR2 (20) NOT NULL
 ,fecha_pago DATE NOT NULL
 );

CREATE OR REPLACE TRIGGER PAGO_JNtrg
  AFTER 
  INSERT OR 
  UPDATE OR 
  DELETE ON PAGO for each row 
 Declare 
  rec PAGO_JN%ROWTYPE; 
  blank PAGO_JN%ROWTYPE; 
  BEGIN 
    rec := blank; 
    IF INSERTING OR UPDATING THEN 
      rec.id_pago := :NEW.id_pago; 
      rec.id_atencion := :NEW.id_atencion; 
      rec.monto := :NEW.monto; 
      rec.tipo_pago := :NEW.tipo_pago; 
      rec.fecha_pago := :NEW.fecha_pago; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      IF INSERTING THEN 
        rec.JN_OPERATION := 'INS'; 
      ELSIF UPDATING THEN 
        rec.JN_OPERATION := 'UPD'; 
      END IF; 
    ELSIF DELETING THEN 
      rec.id_pago := :OLD.id_pago; 
      rec.id_atencion := :OLD.id_atencion; 
      rec.monto := :OLD.monto; 
      rec.tipo_pago := :OLD.tipo_pago; 
      rec.fecha_pago := :OLD.fecha_pago; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      rec.JN_OPERATION := 'DEL'; 
    END IF; 
    INSERT into PAGO_JN VALUES rec; 
  END; 
  /CREATE TABLE region (
    id_region     NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY ( START WITH 1 NOCACHE )
    NOT NULL,
    nombre_region VARCHAR2(80) NOT NULL
)
LOGGING;

ALTER TABLE region ADD CONSTRAINT region_pk PRIMARY KEY ( id_region );


CREATE TABLE REGION_JN
 (JN_OPERATION CHAR(3) NOT NULL
 ,JN_ORACLE_USER VARCHAR2(30) NOT NULL
 ,JN_DATETIME DATE NOT NULL
 ,JN_NOTES VARCHAR2(240)
 ,JN_APPLN VARCHAR2(35)
 ,JN_SESSION NUMBER(38)
 ,id_region NUMBER NOT NULL
 ,nombre_region VARCHAR2 (80) NOT NULL
 );

CREATE OR REPLACE TRIGGER REGION_JNtrg
  AFTER 
  INSERT OR 
  UPDATE OR 
  DELETE ON REGION for each row 
 Declare 
  rec REGION_JN%ROWTYPE; 
  blank REGION_JN%ROWTYPE; 
  BEGIN 
    rec := blank; 
    IF INSERTING OR UPDATING THEN 
      rec.id_region := :NEW.id_region; 
      rec.nombre_region := :NEW.nombre_region; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      IF INSERTING THEN 
        rec.JN_OPERATION := 'INS'; 
      ELSIF UPDATING THEN 
        rec.JN_OPERATION := 'UPD'; 
      END IF; 
    ELSIF DELETING THEN 
      rec.id_region := :OLD.id_region; 
      rec.nombre_region := :OLD.nombre_region; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      rec.JN_OPERATION := 'DEL'; 
    END IF; 
    INSERT into REGION_JN VALUES rec; 
  END; 
  /CREATE TABLE solicitud_examen (
    id_solicitud    NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY ( START WITH 1 NOCACHE )
    NOT NULL,
    id_atencion     NUMBER NOT NULL,
    id_examen       NUMBER NOT NULL,
    estado          VARCHAR2(20) NOT NULL,
    resultado       VARCHAR2(4000),
    fecha_resultado DATE
)
LOGGING;

CREATE INDEX ix_solicitud_examen_atencion ON
    solicitud_examen (
        id_atencion
    ASC );

ALTER TABLE solicitud_examen ADD CONSTRAINT solicitud_examen_pk PRIMARY KEY ( id_solicitud );


CREATE TABLE SOLICITUD_EXAMEN_JN
 (JN_OPERATION CHAR(3) NOT NULL
 ,JN_ORACLE_USER VARCHAR2(30) NOT NULL
 ,JN_DATETIME DATE NOT NULL
 ,JN_NOTES VARCHAR2(240)
 ,JN_APPLN VARCHAR2(35)
 ,JN_SESSION NUMBER(38)
 ,id_solicitud NUMBER NOT NULL
 ,id_atencion NUMBER NOT NULL
 ,id_examen NUMBER NOT NULL
 ,estado VARCHAR2 (20) NOT NULL
 ,resultado VARCHAR2 (4000)
 ,fecha_resultado DATE
 );

CREATE OR REPLACE TRIGGER SOLICITUD_EXAMEN_JNtrg
  AFTER 
  INSERT OR 
  UPDATE OR 
  DELETE ON SOLICITUD_EXAMEN for each row 
 Declare 
  rec SOLICITUD_EXAMEN_JN%ROWTYPE; 
  blank SOLICITUD_EXAMEN_JN%ROWTYPE; 
  BEGIN 
    rec := blank; 
    IF INSERTING OR UPDATING THEN 
      rec.id_solicitud := :NEW.id_solicitud; 
      rec.id_atencion := :NEW.id_atencion; 
      rec.id_examen := :NEW.id_examen; 
      rec.estado := :NEW.estado; 
      rec.resultado := :NEW.resultado; 
      rec.fecha_resultado := :NEW.fecha_resultado; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      IF INSERTING THEN 
        rec.JN_OPERATION := 'INS'; 
      ELSIF UPDATING THEN 
        rec.JN_OPERATION := 'UPD'; 
      END IF; 
    ELSIF DELETING THEN 
      rec.id_solicitud := :OLD.id_solicitud; 
      rec.id_atencion := :OLD.id_atencion; 
      rec.id_examen := :OLD.id_examen; 
      rec.estado := :OLD.estado; 
      rec.resultado := :OLD.resultado; 
      rec.fecha_resultado := :OLD.fecha_resultado; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      rec.JN_OPERATION := 'DEL'; 
    END IF; 
    INSERT into SOLICITUD_EXAMEN_JN VALUES rec; 
  END; 
  /ALTER TABLE atencion
    ADD CONSTRAINT fk_atencion_esp FOREIGN KEY ( id_especialidad )
        REFERENCES especialidad ( id_especialidad )
    NOT DEFERRABLE;

ALTER TABLE atencion
    ADD CONSTRAINT fk_atencion_medico FOREIGN KEY ( rut_medico )
        REFERENCES medico ( rut_medico )
    NOT DEFERRABLE;

ALTER TABLE atencion
    ADD CONSTRAINT fk_atencion_paciente FOREIGN KEY ( rut_paciente )
        REFERENCES paciente ( rut_paciente )
    NOT DEFERRABLE;

ALTER TABLE comuna
    ADD CONSTRAINT fk_comuna_region FOREIGN KEY ( id_region )
        REFERENCES region ( id_region )
    NOT DEFERRABLE;

ALTER TABLE medico
    ADD CONSTRAINT fk_medico_afp FOREIGN KEY ( id_afp )
        REFERENCES afp ( id_afp )
    NOT DEFERRABLE;

ALTER TABLE medico
    ADD CONSTRAINT fk_medico_esp FOREIGN KEY ( id_especialidad )
        REFERENCES especialidad ( id_especialidad )
    NOT DEFERRABLE;

ALTER TABLE medico
    ADD CONSTRAINT fk_medico_inst FOREIGN KEY ( id_institucion_salud )
        REFERENCES institucion_salud ( id_institucion_salud )
    NOT DEFERRABLE;

ALTER TABLE medico
    ADD CONSTRAINT fk_medico_supervisor FOREIGN KEY ( rut_supervisor )
        REFERENCES medico ( rut_medico )
    NOT DEFERRABLE;

ALTER TABLE paciente
    ADD CONSTRAINT fk_paciente_comuna FOREIGN KEY ( id_comuna )
        REFERENCES comuna ( id_comuna )
    NOT DEFERRABLE;

ALTER TABLE pago
    ADD CONSTRAINT fk_pago_atencion FOREIGN KEY ( id_atencion )
        REFERENCES atencion ( id_atencion )
    NOT DEFERRABLE;

ALTER TABLE solicitud_examen
    ADD CONSTRAINT fk_solicitud_atencion FOREIGN KEY ( id_atencion )
        REFERENCES atencion ( id_atencion )
    NOT DEFERRABLE;

ALTER TABLE solicitud_examen
    ADD CONSTRAINT fk_solicitud_examen FOREIGN KEY ( id_examen )
        REFERENCES examen ( id_examen )
    NOT DEFERRABLE;

CREATE OR REPLACE TRIGGER trg_atencion_check_medico_esp 
    BEFORE INSERT OR UPDATE ON ATENCION 
    FOR EACH ROW 
DECLARE
  v_esp NUMBER;
BEGIN
  SELECT id_especialidad INTO v_esp FROM MEDICO WHERE rut_medico = :NEW.rut_medico;
  IF v_esp IS NULL THEN
    RAISE_APPLICATION_ERROR(-20003, 'Médico sin especialidad registrada.');
  ELSIF v_esp != :NEW.id_especialidad THEN
    RAISE_APPLICATION_ERROR(-20004, 'La especialidad de la atención no coincide con la especialidad del médico.');
  END IF;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(-20005, 'Médico no existe.');
END; 
/

CREATE OR REPLACE TRIGGER trg_medico_no_double_booking 
    BEFORE INSERT OR UPDATE ON ATENCION 
    FOR EACH ROW 
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM ATENCION a
    WHERE a.rut_medico = :NEW.rut_medico
      AND a.fecha_hora = :NEW.fecha_hora
      AND a.id_atencion != NVL(:NEW.id_atencion,-1);

  IF v_count > 0 THEN
    RAISE_APPLICATION_ERROR(-20002, 'Conflicto de agenda: el médico ya tiene una atención en ese horario.');
  END IF;
END; 
/

CREATE OR REPLACE TRIGGER trg_medico_no_self_supervisor 
    BEFORE INSERT OR UPDATE ON MEDICO 
    FOR EACH ROW 
BEGIN
  IF :NEW.rut_supervisor IS NOT NULL AND :NEW.rut_supervisor = :NEW.rut_medico THEN
    RAISE_APPLICATION_ERROR(-20001, 'Un médico no puede ser su propio supervisor.');
  END IF;
END; 
/

CREATE OR REPLACE TRIGGER trg_solicitud_exam_result_dates 
    BEFORE INSERT OR UPDATE ON SOLICITUD_EXAMEN 
    FOR EACH ROW 
BEGIN
  IF :NEW.estado = 'completado' AND :NEW.fecha_resultado IS NULL THEN
    RAISE_APPLICATION_ERROR(-20006, 'Si el estado es COMPLETADO, fecha_resultado debe tener valor.');
  END IF;

  IF :NEW.fecha_resultado IS NOT NULL AND :NEW.estado != 'completado' THEN
    RAISE_APPLICATION_ERROR(-20007, 'Si existe fecha_resultado, el estado debe ser COMPLETADO.');
  END IF;
END; 
/



-- Informe de Resumen de Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            11
-- CREATE INDEX                             4
-- ALTER TABLE                             27
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           4
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
