
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template


jdbc.url=jdbc:mysql://localhost:3306/Computec_DB?useSSL=false&serverTimezone=America/Santiago&allowPublicKeyRetrieval=true
jdbc.user=grupo6
jdbc.password=Grupo625
jdbc.driver=com.mysql.cj.jdbc.Driver
